server:
  port: 8083
  ssl:
    enabled: true
    key-store: classpath:keystore/tim17.p12
    key-store-password: septim17
    key-alias: tim17

eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true

zuul:
  sslHostnameValidationEnabled: false

ribbon:
  IsSecure: true
